service: administration-users

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment:
    AWS_ACCESS_KEY_ID: AKIA26WDU3SB3RTPFMBE
    AWS_SECRET_ACCESS_KEY: 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
    REGION: us-east-1
    API_VERSION: 2012-08-10

functions:
  getAcessNumber:
    handler: analyzeAccess.getAcessNumber
    events:
      - http:
          path: /get-acess
          method: GET
  incrementAcessNumber:
    handler: analyzeAccess.incrementAcessNumber
    events:
      - http:
          path: /increment-acess
          method: GET
  getUserById:
    handler: managementUsers.getUserById
    events:
      - http:
          path: /get-user/{user_id}
          method: GET
  createUser:
    handler: managementUsers.createUser
    events:
      - http:
          path: /create-user
          method: POST

plugins:
  - serverless-offline
