service: administration-users

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  # environment:
  #   AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
  #   AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
  #   AWS_REGION: us-REGION-1

functions:
  getAcessNumber:
    handler: analyzeAccess.getAcessNumber
    events:
      - http:
          path: /get-acess
          method: GET

  incrementAcessNumber:
    handler: analyzeAccess.incrementAcessNumber
    events:
      - http:
          path: /increment-acess
          method: GET

  getUserByLogin:
    handler: managementUsers.getUserByLogin
    events:
      - http:
          path: /get-user/{user_login}
          method: GET

  createUser:
    handler: managementUsers.createUser
    events:
      - http:
          path: /create-user
          method: POST
